/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as NorrisRouteImport } from './routes/norris'
import { Route as MoosRouteImport } from './routes/moos'
import { Route as FlynnRouteImport } from './routes/flynn'
import { Route as DaantjeRouteImport } from './routes/daantje'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const NorrisRoute = NorrisRouteImport.update({
  id: '/norris',
  path: '/norris',
  getParentRoute: () => rootRouteImport,
} as any)
const MoosRoute = MoosRouteImport.update({
  id: '/moos',
  path: '/moos',
  getParentRoute: () => rootRouteImport,
} as any)
const FlynnRoute = FlynnRouteImport.update({
  id: '/flynn',
  path: '/flynn',
  getParentRoute: () => rootRouteImport,
} as any)
const DaantjeRoute = DaantjeRouteImport.update({
  id: '/daantje',
  path: '/daantje',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/daantje': typeof DaantjeRoute
  '/flynn': typeof FlynnRoute
  '/moos': typeof MoosRoute
  '/norris': typeof NorrisRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/daantje': typeof DaantjeRoute
  '/flynn': typeof FlynnRoute
  '/moos': typeof MoosRoute
  '/norris': typeof NorrisRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/daantje': typeof DaantjeRoute
  '/flynn': typeof FlynnRoute
  '/moos': typeof MoosRoute
  '/norris': typeof NorrisRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/daantje'
    | '/flynn'
    | '/moos'
    | '/norris'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all' | '/daantje' | '/flynn' | '/moos' | '/norris' | '/videos'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/daantje'
    | '/flynn'
    | '/moos'
    | '/norris'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  DaantjeRoute: typeof DaantjeRoute
  FlynnRoute: typeof FlynnRoute
  MoosRoute: typeof MoosRoute
  NorrisRoute: typeof NorrisRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/norris': {
      id: '/norris'
      path: '/norris'
      fullPath: '/norris'
      preLoaderRoute: typeof NorrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moos': {
      id: '/moos'
      path: '/moos'
      fullPath: '/moos'
      preLoaderRoute: typeof MoosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flynn': {
      id: '/flynn'
      path: '/flynn'
      fullPath: '/flynn'
      preLoaderRoute: typeof FlynnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daantje': {
      id: '/daantje'
      path: '/daantje'
      fullPath: '/daantje'
      preLoaderRoute: typeof DaantjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  DaantjeRoute: DaantjeRoute,
  FlynnRoute: FlynnRoute,
  MoosRoute: MoosRoute,
  NorrisRoute: NorrisRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
